pipeline {
    agent any
    
    environment{
        JWT_SECRET = '[?m-A9+^/(A5VK]p}gZ_Jr@ZuRa%5:ng'
    }

    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                bat 'cd frontend && npm install'
                bat 'cd backend && npm install'
            }
        }
        stage('Run unit test') {
            steps {
                bat 'cd frontend && npm run test:unit'
                publibatHTML target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: "./coverage/lcov-report",
                    reportFiles: "index.html",
                    reportName: 'Unit Test Coverage Report'
                ]

                publishHTML target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: "./coverage",
                    reportFiles: "report.html",
                    reportName: 'Unit Test Report'
                ]
            }
        }
        stage('Run component test') {
            steps {
                bat 'cd frontend && npm run test:component'
            }
        }
        stage("Code coverage report") {
            steps {
                clover(cloverReportDir: 'frontend/coverage', cloverReportFileName: 'clover.xml',
                    healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
                    unhealthyTarget: [methodCoverage: 50, conditionalCoverage: 50, statementCoverage: 50],
                    failingTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0]
                )
            }
        }
    }
}