version: "3"

secrets:
  ATLAS_URI:
    external: true
  ATLAS_TEST_URI:
    external: true
  AWS_ID:
    external: true
  AWS_SECRET:
    external: true
  S3_BUCKET_NAME:
    external: true
  JWT_SECRET:
    external: true

services:
  frontend:
    image: 808218764127/team-8-frontend:1.0.0
    ports:
      - "9999:5000"
  backend:
    image: 808218764127/team-8-backend:1.0.0
    secrets:
      - ATLAS_URI
      - ATLAS_TEST_URI
      - AWS_ID
      - AWS_SECRET
      - S3_BUCKET_NAME
      - JWT_SECRET
    environment:
      - ATLAS_URI_FILE=/run/secrets/ATLAS_URI
      - ATLAS_TEST_URI_FILE=/run/secrets/ATLAS_TEST_URI
      - AWS_ID_FILE=/run/secrets/AWS_ID
      - AWS_SECRET_FILE=/run/secrets/AWS_SECRET
      - S3_BUCKET_NAME_FILE=/run/secrets/S3_BUCKET_NAME
      - JWT_SECRET_FILE=/run/secrets/JWT_SECRET
    ports:
      - "9999:8081"
